### ISSUE TITLE
Make a test that all bindist URLs exist.

### ISSUE THREAD

**Issue by phadej** [haskell/ghcup-metadata#105]
E.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS to check that files exist, or actually `GET` but not reading the body (not so nice for the server).

Issues like #104  or #102 are relatively easily preventable.

**Comment by hasufell** [comment]
- https://github.com/haskell/ghcup-metadata/blob/develop/.github/workflows/bindists.yaml
- https://github.com/haskell/ghcup-metadata/actions/workflows/bindists.yaml
- https://github.com/haskell/ghcup-metadata/commit/d309865d0213c55e200938f7d092b59cfa256022 (reverted)

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/5721827769/job/15503993773

**Comment by phadej** [comment]
CI in https://github.com/haskell/ghcup-metadata/pull/101 was green, the simple mistake of a typo is caught too late. 

Installing bindists is longer test, but just checking that artifacts exists aren't and can be run on every PR&commit.

**Comment by hasufell** [comment]
> Installing bindists is a long running test, but just checking that artifacts exists aren't and can be run on every PR&commit.

Installing bindists can/should be tested on every PR that adds new bindists or explicitly on `develop` branch.

That's what the job is for. End users don't care whether the bindist exists. Don't push things that can't be installed. They are broken.

The idea was to use comments/description in th PR text to trigger the right bindist action (tool, version and metadata file). But the actions are messy. Feel free to fix it or create autodetection of those details based on a yaml diff.

**Comment by hasufell** [comment]
> Please fix the incorrect metadata. You reviewed #101, and didn't trigger the CI.

I didn't review. I gave @bgamari the go ahead to merge and manage without my involvement.
