### ISSUE TITLE
Resolve the gpg signing issues

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-metadata#112]
@bgamari @wz1000 sorry for the drastic measures, but I revoked push access until we figure out what's going on here. I did not have enough time to verify that the cross signing has succeeded and which keys exactly we need to use.

The gpg feature is not about convenience. It's a **security** feature and it's important that we get it right, even if it's off by default. Also see https://github.com/haskell/ghcup-hs/issues/858

I sent an email to both your WT addresses with your pubkeys cross signed. The idea was that you will then import them and upload them (uploading for other people is discouraged).

I still don't know if you received that mail. If you did not, why? Did you check your spam filter? These emails need to be valid and available for end-users to contact you in private for key verification.

I followed these instructions: https://gist.github.com/F21/b0e8c62c49dfab267ff1d0c6af39ab84

So let's clear up some confusion:

1. did you received my email?
2. which are your keys exactly?
    - from Ben I now have two keys and I don't know which one to use:
      - [0x73EDE9E8CFBAEF01](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x73EDE9E8CFBAEF01) was expired last time I checked and is only cross-signed by me, but not by Zubin
      - [0x2de04d4e97db64ad](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x2de04d4e97db64ad) is cross signed by Zubin, but not by me (because apparently Ben did not receive my email with the signed pubkey)
    - from Zubin, I'm guessing it's [0x588764fbe22d19c4](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x588764fbe22d19c4) but it's neither cross-signed by Ben, nor by me

**Comment by hasufell** [comment]
Key verification will now be done in CI during the bindist install action: https://github.com/haskell/ghcup-metadata/blob/develop/.github/workflows/test-sigs.sh

The keys are in that shell script.

**Comment by hasufell** [comment]
https://github.com/haskellfoundation/error-message-index/pull/458

**Comment by wz1000** [comment]
My key is cross signed by Ben

![2023-08-26-171325_grab](https://github.com/haskell/ghcup-metadata/assets/4812498/048e1d55-5f25-47f2-b43a-e9223cd24d5d)

**Comment by bgamari** [comment]
I do not appear to have received your email. I have inquired internally to determine why that might be the case.

**Comment by bgamari** [comment]
As noted on the [GHC download pages](https://www.haskell.org/ghc/download_ghc_9_6_1.html) I sign GHC-related artifacts using my `ben@well-typed.com` key ([FFEB7CE81E16A36B3E2DED6F2DE04D4E97DB64AD](https://keyserver.ubuntu.com/pks/lookup?search=FFEB7CE81E16A36B3E2DED6F2DE04D4E97DB64AD&fingerprint=on&op=index), which I have cross-signed using my personal keys. As such, even if you have signed my personal key, there should be a chain of trust between the key you have signed (which appears to be my personal key) and the key used for GHC work.

As noted above, my personal key ([0x73EDE9E8CFBAEF01](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x73EDE9E8CFBAEF01)) is not expired.

**Comment by bgamari** [comment]
@hasufell we have identified the mail hiccup. Our spam filter (`rspamd`) indeed seems to have a nasty habit of classifying ASCII-armored PGP messages as spam. We have zeroed the weight of the feature responsible for this classification. It would be appreciated if you could try resending your message to ensure that the issue is resolved.

**Comment by hasufell** [comment]
I have forwarded the original email.

**Comment by hasufell** [comment]
I see my cross signature in both of your keys now. The cross sig for my key can be done later.

Bens non-WT key does indeed seem not expired, so I probably made a mistake there.

documentation PR is merged: https://github.com/haskell/ghcup-hs/pull/873
updated: https://www.haskell.org/ghcup/guide/#gpg-verification

**Comment by hasufell** [comment]
Push access should be restored.

It's a little bit awkward though that we don't have nicer way to propagate keychain changes to end users, but the HF error index should be good enough for now: https://github.com/haskellfoundation/error-message-index/pull/458

Thanks for your understanding.

**Comment by bgamari** [comment]
Thanks, @hasufell ! I'll try to send along your signed key today.
