### ISSUE TITLE
Stack - Recommended, Latest

### ISSUE THREAD

**Issue by mpilgrem** [haskell/ghcup-metadata#118]
From the perspective of the Stack project, there is no reason for GHCup not to recommend the latest Stack release, at any point - Stack aims to have a high degree of backwards compatibility and it would become clear within a few weeks of any release if there were any undetected regressions introduced into a release.

**Comment by hasufell** [comment]
@bgamari I'm assuming you're watching the repository?

**Comment by bgamari** [comment]
Yes, but the notifications weren't making it into my inbox.

**Comment by bgamari** [comment]
Yes, but the notifications weren't making it into my inbox.
