### ISSUE TITLE
GHC 9.0.2 is here

### ISSUE THREAD

**Issue by jrp2014** [haskell/ghcup-metadata#12]
It would be good to sync updating the metadata here with each ghc release.

**Comment by hasufell** [comment]
My laptop is in repair and I don't have access to my gpg key atm. So @bgamari would have to do it

**Comment by hasufell** [comment]
Or @gbaz 

Not sure how to communicate the different gpg key though. 
 https://www.haskell.org/ghcup/guide/#gpg-verification

**Comment by phadej** [comment]
ping @bgamari, @gbaz

**Comment by hasufell** [comment]
I'm on it folks.

**Comment by hasufell** [comment]
Done
