### ISSUE TITLE
Validate tags in CI

### ISSUE THREAD

**Issue by bgamari** [haskell/ghcup-metadata#135]
Currently it's very easy to overlook or otherwise mess up the tags when adding a new tool version. CI should ideally perform some consistency checks to catch this failure mode:

 * tags should be valid (matching a regular expression capturing known tags)
 * there should be one `Latest` and one `LatestPrerelease`, and one `Recommended` version for each tool
 * each `ghc` tool should have a `base-...` tag

**Comment by hasufell** [comment]
CI already does that: 

- https://github.com/haskell/ghcup-metadata/blob/1d366edea606e64d14177c36ca49e5a8b351400e/ghcup-gen/Validate.hs#L126
- https://github.com/haskell/ghcup-metadata/blob/1d366edea606e64d14177c36ca49e5a8b351400e/.github/workflows/test.yaml#L75

That can probably be extended.

**Comment by hasufell** [comment]
Done: https://github.com/haskell/ghcup-metadata/pull/137

![Screenshot_2023-10-01_16-19-28](https://github.com/haskell/ghcup-metadata/assets/1241845/6443464e-d164-4c53-9300-32a1d40c0b45)

Example pipeline on prereleases: https://github.com/haskell/ghcup-metadata/actions/runs/6369219389/job/17289264412#step:10:18
