### ISSUE TITLE
Document tag meanings

### ISSUE THREAD

**Issue by bgamari** [haskell/ghcup-metadata#136]
While looking through `ghcup-prereleases-0.0.7.yaml` I realized that I have no idea what the intended semantics of the `old` tag are. We should probably have a canonical reference document describing the set of valid tags (and check consistency as described in #135).

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/commit/c0ffb22d6af079af54285edfc3fd413ead29d75b

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/commit/335bc378aac36221ddfb5fb42bba0d2df80fac34
