### ISSUE TITLE
Update `hls-powered` tags for GHC 9.4 and higher

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-metadata#143]
The `hls-powered` tags produced by `ghcup list` do not match what is written at: https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html

<img width="493" alt="Screenshot 2023-10-30 at 10 21 21" src="https://github.com/haskell/ghcup-metadata/assets/1155218/3a400f4c-097b-4588-834f-72d72e26e2c9">

<img width="473" alt="Screenshot 2023-10-30 at 10 21 53" src="https://github.com/haskell/ghcup-metadata/assets/1155218/f3077355-84e7-4c49-a0b9-0275bce8f963">

**Comment by phadej** [comment]
as far as I understand `hls-powered` is dynamic, and  I'm not 100% sure on what it depends.

 see e.g. https://github.com/haskell/ghcup-metadata/blob/c806339f69e6e7bda7302d4ddbed4bab66ebf686/hls-metadata-0.0.1.json#L1347: 

```
            "Linux_Ubuntu": [
                "9.0.2",
                "9.2.8",
                "9.4.7",
                "9.6.3",
                "9.8.1"
            ],
```

which matches HLS docs.

After installing HLS-2.4.0.0 and *setting that version as the default** (two checkmarks), I have:

![Screenshot from 2023-10-30 11-54-49](https://github.com/haskell/ghcup-metadata/assets/51087/8dfb7c6c-1e13-4b81-9433-8852cfdbb2d2)

**Comment by hasufell** [comment]
> as far as I understand hls-powered is dynamic, and I'm not 100% sure on what it depends.

Depends on files:

- https://github.com/haskell/ghcup-hs/blob/59bfdd9a307cd69c22c956132750e2058b2872c2/lib/GHCup/List.hs#L171
- https://github.com/haskell/ghcup-hs/blob/59bfdd9a307cd69c22c956132750e2058b2872c2/lib/GHCup/Utils.hs#L583

The list you mention is generated:

- https://github.com/haskell/ghcup-metadata/blob/c806339f69e6e7bda7302d4ddbed4bab66ebf686/ghcup-gen/Main.hs#L230
- https://github.com/haskell/ghcup-metadata/blob/c806339f69e6e7bda7302d4ddbed4bab66ebf686/ghcup-gen/Generate.hs#L152

**Comment by hasufell** [comment]
To give more context: https://github.com/haskell/ghcup-metadata/blob/c806339f69e6e7bda7302d4ddbed4bab66ebf686/hls-metadata-0.0.1.json is actually not used by ghcup at all, only be VSCode Haskell extension. I have not figured out yet how to embed it in GHCup itself (it's also up to discussion whether that's the right place), because it would be an additional download or a non-trivial change to the current metadata.

One idea was to only provide this feature in the TUI, since that has a more interactive feeling. CLI is optimized for being responsive and non-interactive.

**Comment by andreasabel** [comment]
I see.  Following @phadej's recipe I am now also seeing my latest GHC minor versions `hls-powered`.

Maybe a minimal fix for this issue would be to name the tag `hls-$VERSION-powered`, so I would see `hls-2.4.0.0-powered`.  This would nudge me towards seeing the connection between the `hls-powered` and the current default version of `hls`.  The full story would then be discoverable (by experimenting with `ghcup set hls`).

**Comment by hasufell** [comment]
I believe we can solve this through more information via https://github.com/haskell/ghcup-hs/pull/850
