### ISSUE TITLE
Question: what is the difference between ghcup-0.0.7.yaml vs ghcup-0.0.8.yaml ?

### ISSUE THREAD

**Issue by evan0greenup** [haskell/ghcup-metadata#145]
It seems that `ghcup-0.0.7.yaml` is more up-to-date than `ghcup-0.0.8.yaml`. 

Why there is different YAML version for each channel? Because when new version of Haskell tools release, the maintainer will append that version to YAML file instead of overwrite it.

Can anyone give me some explanation?

**Comment by hasufell** [comment]
> Why there is different YAML version for each channel?

Because the formats are not compatible. ghcup 0.1.19.4 may fail to parse `ghcup-0.0.8.yaml`.

> Because when new version of Haskell tools release, the maintainer will append that version to YAML file instead of overwrite it.

I don't understand this.
