### ISSUE TITLE
Add cabal-install 3.10.2.1

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-metadata#147]
Issue opened for tracking
- https://github.com/haskell-actions/setup/pull/53

@Kleidukos once you added `3.10.2.1` here, please close this issue.

**Comment by Kleidukos** [comment]
@andreasabel no need, see the description of https://github.com/haskell/cabal/pull/9416

**Comment by andreasabel** [comment]
Ok, then I should also not support this version in `haskell-actions/setup`.

**Comment by Kleidukos** [comment]
Yes no need :)
