### ISSUE TITLE
ghcup tui fails. Error in $.ghcupDownloads.Cabal['3.10.2.1'].viArch['A_64']['Linux_Rocky']: Unexpected failure in decoding LinuxDistro: "Rocky"

### ISSUE THREAD

**Issue by tonyalaribe** [haskell/ghcup-metadata#163]
I think a recent change just introduced this issue, since our CI started failing with the error this morning, and ran fine yesterday. 

Running ghcup tui also brings up this error:

<img width="1087" alt="CleanShot 2024-01-04 at 14 27 12@2x" src="https://github.com/haskell/ghcup-metadata/assets/6564482/cde8acca-a70b-4653-9ca6-b6676b2b41ee">

**Comment by hasufell** [comment]
Thanks. This will be fixed in a minute.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/commit/4f3a14ed90866fc388c6bf50fdaa3e4011c94ad5
