### ISSUE TITLE
No i386 bindists for recent releases for alpine linux. 

### ISSUE THREAD

**Issue by phadej** [haskell/ghcup-metadata#214]
AFAICS there aren't i386 alpine releases for 9.6, 9.8 or 9.10

is this ghcup metadata issue or isn't GHC producing i386 alpine bindists anymore?

**Comment by mpilgrem** [comment]
In respect of the GHC project, I can't see any reference to Alpine Linux at https://www.haskell.org/ghc/download_ghc_9_10_1.html#linux_i386, for example.

**Comment by hasufell** [comment]
> AFAICS there aren't i386 alpine releases for 9.6, 9.8 or 9.10
> 
> is this ghcup metadata issue or isn't GHC producing i386 alpine bindists anymore?
> 
> 

It never did. I always built them manually. I just stopped doing so out of laziness it seems. I think there also were some issues, but I don't remember them. So I'll have to give it another go.

**Comment by phadej** [comment]
I'd like to have alpine bindists in the future too. These make it a lot easier to create bindists (though I don't create 32bit ones), *and* test 32bit compatibility in libraries.

**Comment by hasufell** [comment]
> I'd like to have alpine bindists in the future too. These make it a lot easier to create bindists (though I don't create 32bit ones), _and_ test 32bit compatibility in libraries (which i care somewhat, as issues do get reported)

We will have to add that to the bindist CI then:

https://github.com/haskell/ghcup-metadata/blob/4b76ca1a8e39da64c686dcf0f455ff1a42ea18d8/.github/workflows/bindists.yaml#L40-L95
