### ISSUE TITLE
Update README.md instructions

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/ghcup-metadata#238]
As a maintainer of one of the tools distributed by GHCup (`cabal-install`), I'd like to understand what it takes to get a new release added to  GHCup, both `vanilla` and main channel. The current description in README is outdated and covers only GHC, which was mentioned in Cabal's Matrix room recently:

```
geekosaur: the instructions say to add to both regular and vanilla but vanilla for 3.10.3 had fbsd bindists in it
maerwald: those instructions are outdated then
geekosaur: (said instructions only really talk about ghc, also) README.md for ghcup-metadata develop
maerwald: yeah, I should probably update them
```

I'd be happy to review a PR updating the README and provide feedback on how well I am able to comprehend it.

Ideally, we'd like to be able to add a new version of `cabal` to the `vanilla` channel (at least) **before** the release is announced on Discourse. Does that sound feasible? If there's something that we can do to get it into the main channel before the announcement, that would be even better.

**Comment by hasufell** [comment]
Done.

**Comment by ulysses4ever** [comment]
Thanks!
