### ISSUE TITLE
Add `ghcup-latest.yaml` that always points to the newest version of metadata file

### ISSUE THREAD

**Issue by StephenChips** [haskell/ghcup-metadata#32]
# Why

So that we don't have to change the source manually, and can always get the newest tools by just checking `ghcup list`.

**Comment by hasufell** [comment]
Uhm. ghcup metadata has a format. This format is sometimes extended in a backwards incompatible way. There's a reason these are versioned. If a GHC is missing from an old metadata file, there's a chance that's on purpose too.
