### ISSUE TITLE
Update stack to v2.9.1

### ISSUE THREAD

**Issue by andys8** [haskell/ghcup-metadata#36]
A new version of stack was released. No idea how one would update stack metadata, though. Would be cool, if added to README instructions.

https://github.com/commercialhaskell/stack/releases/tag/v2.9.1

**Comment by andreasabel** [comment]
Looks like this was fixed by https://github.com/haskell/ghcup-metadata/commit/38af24534d032695a2bf5b94e507458d92458ebc.
