### ISSUE TITLE
cabal 3.8 could get recommended perhaps?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/ghcup-metadata#40]
It's been several months. Several regressions exist but nothing egregious. So, maybe we can get the badge for ~~3.7~~ 3.8?

**Comment by ulysses4ever** [comment]
3.7 -> 3.8 of course

**Comment by hasufell** [comment]
There are a lot of user visible regressions:

* https://github.com/haskell/cabal/issues/8455
* https://github.com/haskell/cabal/issues/8478
* https://github.com/haskell/cabal/issues/8494
* https://github.com/haskell/cabal/issues/8562
* https://github.com/haskell/cabal/issues/8058
* https://github.com/haskell/cabal/issues/8458

Some of these seem severe to me.

**Comment by ulysses4ever** [comment]
Thank you for the answer.
