### ISSUE TITLE
Support GHC 9.2.6

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-metadata#74]
GHC 9.2.6 has been released:
- https://www.haskell.org/ghc/download_ghc_9_2_6.html

NB. Support for new GHCs is usually swift in GHCup, I opened this issue mostly for tracking purposes.

**Comment by phadej** [comment]
It is supported, isn't it? At least `haskell-ci` works

**Comment by andreasabel** [comment]
Ah, indeed, thanks!

**Comment by andreasabel** [comment]
I am sorry I caused 2 failing runs of the `bindist` CI here, and @phadej's answer caused another one, and this very comment will cause another one.  Isn't this CI a bit nervous?
https://github.com/haskell/ghcup-metadata/blob/2941394cb19ecc9772ac9b72f5d5ccb71a133355/.github/workflows/bindists.yaml#L8-L9
