### ISSUE TITLE
Is there a way to know whether vanilla and main release channels have the same bindists

### ISSUE THREAD

**Issue by phadej** [haskell/ghcup-metadata#85]
I added vanilla release channel to be able to install GHC-9.6.1, and now my builds started failing on GHC-9.0.2

Is GHC-9.0.2 bindists in the main release channel different? Is there away  to add a release-channel so it doesn't override anything in main channel?

```
<no location info>: error:
    <command line>: /github/home/.cabal/store/ghc-9.0.2/regex-base-0.94.0.2-74ad7a23e807bdf2[42](https://github.com/haskell-CI/haskell-ci/actions/runs/4397158283/jobs/7701773044#step:21:43)4625a40f382dedae9acc7d83e88b587217df1216929b61/lib/libHSregex-base-0.94.0.2-74ad7a23e807bdf2424625a40f382dedae9acc7d83e88b587217df1216929b61-ghc9.0.2.so: undefined symbol: base_GHCziBase_zpzpzuzdszpzp_info
```

**Comment by hasufell** [comment]
Yes there is. I'm currently on mobile, so can't guarantee this works:

```yaml
OwnSource:
  - https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-vanilla-0.0.7.yaml
  - https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-0.0.7.yaml
```

This wi cause ghcup to only use versions of vanilla that don't exist in the proper channel. 

Note that a crapload of bindists in vanilla are busted due to hadrian bugs that I fixed manually. 

Also note that 9.6.1 is in the proper channel too now.

**Comment by hasufell** [comment]
You have to set this.in config.yaml manually, more information here: https://github.com/haskell/ghcup-hs/blob/c20deceaa8189a1f3034335759b84132f9a9ef82/data/config.yaml#L59

**Comment by phadej** [comment]
> Also note that 9.6.1 is in the proper channel too now.

It is, but `cabal-install-3.10.1.0` isn't.

Where I need to put that `OwnSource`. is there a way to do that with `ghcup config` (e.g. `add-release-channel --first`). Would such feature be welcome?

**Comment by hasufell** [comment]
> It is, but cabal-install-3.10.1.0 isn't.

It is. I just added it before I went to the pub.

> Where I need to put that OwnSource. is there a way to do that with ghcup config (e.g. add-release-channel --first). Would such feature be welcome?

Yes too, `ghcup config` should accept json string of the yaml I provided. Might need some experimentation to figure out how.exactly. again, am on mobile.

**Comment by phadej** [comment]
> should accept json string of the yaml 

I'd rather not try to write yaml inside shell scripts. Nor it's really good user experience anyway.

I'll prefer a flag to `add-release-channel` subcommand to do what I need, as the command is already there.

**Comment by hasufell** [comment]
> I'd rather not try to write yaml inside shell scripts. Nor it's really good user experience anyway.

No, the parser doesn't care whether you write yaml or json.

**Comment by phadej** [comment]
Ok. I'll stay away from vanilla channel.

**Comment by hasufell** [comment]
I'll post a working version once I get home. It's really trivial, just not documented well.

**Comment by hasufell** [comment]
Here you go:

```sh
ghcup config set url-source '{OwnSource: ["https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-vanilla-0.0.7.yaml", "https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-0.0.7.yaml"] }'
```
