### ISSUE TITLE
New GPG key does not contain a user ID; `gpg --recv-keys` fails

### ISSUE THREAD

**Issue by sidkshatriya** [haskell/ghcup-metadata#87]
Recently the gpg key used to sign the the ghcup `ghcup-0.0.7.yaml` file changed.

When following the [updated](https://github.com/haskell/ghcup-hs/commit/afcb4828663b79a0415077a8430e5ec7eb5e0021) instructions at https://www.haskell.org/ghcup/guide/#gpg-verification I get the following message:

```
$ gpg --batch --keyserver keys.openpgp.org     --recv-keys 7D1E8AFD1D4A16D71FADA2F2CCC85C0E40C06A8C
gpg: key CCC85C0E40C06A8C: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

So, while the key is found, it does not get imported as it does not have any user ID associated with it.

The impact of this is that ghcup verification when doing `ghcup tui` fails predictably as `[ Error ] [GHCup-00210] GPG verify failed: GPG verify failed`

Manually trying to verify the yaml results in the following

```
$ gpg --verify ghcup-0.0.7.yaml.sig ghcup-0.0.7.yaml
gpg: Signature made Thu Mar 30 21:04:04 2023 IST
gpg:                using RSA key 7D1E8AFD1D4A16D71FADA2F2CCC85C0E40C06A8C
gpg:                issuer "hasufell@posteo.de"
gpg: Can't check signature: No public key
```

Interestingly here there is some sort of user id attached to the signature.

**Comment by hasufell** [comment]
Can you try a different key server?

**Comment by sidkshatriya** [comment]
Thanks -- that worked. I changed the key server to pgp.mit.edu and that did the trick.
